### PR TITLE
Updated the CF STS guide and removed obsolete information and steps.

### PR DESCRIPTION
**Pull request by nierajsingh**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@nierajsingh Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-sts-cloud-foundry-deployment&pullRequestId=1)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-sts-cloud-foundry-deployment&pullRequestId=1) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by dsyer** [comment]
These changes are already on master (with your name on them). Thanks anyway.

P.S. you should change your email address to pivotal.io for the git log.

**Comment by nierajsingh** [comment]
Thanks for looking at this PR. I did a clean clone and pulled from master, and I don't see the two new commits. I also don't see them in the list of commits in master via the web UI.

https://github.com/spring-guides/gs-sts-cloud-foundry-deployment/pull/1/commits/06c9ee2632ad6833b6ebbf19810c2710792d03f4

https://github.com/spring-guides/gs-sts-cloud-foundry-deployment/pull/1/commits/1466bc894145ca859b3691f622fd88b0a2cba907

**Comment by pivotal-issuemaster** [comment]
@nierajsingh Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-sts-cloud-foundry-deployment&pullRequestId=1)!

**Comment by dsyer** [comment]
Right, you have 2 forks of this repo apparently. I was looking at the one with the default name, but the PR is actually from `gs-sts-cloud-foundry-deployment-1`. I see those commits there. Merged in 1466bc8, thanks.

**Comment by nierajsingh** [comment]
Thank you very much.

**Pull request merged**
